const os=require('os');
console.log(os.freemem())
console.log(os.homedir())
console.log(os.availableParallelism())
console.log(os.userInfo())
console.log(os.hostname())
console.log(os.release())
console.log(os.platform())
console.log(os.loadavg())
console.log(os.tmpdir())
console.log(os.totalmem())
console.log(os.type())
console.log(os.uptime())
console.log(os.networkInterfaces())
console.log(os.machine())

const path=require('path')
